/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

 module.exports = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{ type: 'autogenerated', dirName: '.' }],

  gettingstarted: [
      {
      type: 'category',
      label: 'Getting Started',
      collapsed: true,
      items: [
        'guides/neosound-quick-start',
        'guides/curation-protocol-quickstart',
      ],
    },
    {
      type: 'category',
      label: 'Curation Protocol',
      collapsed: true,
      items: [
        'curation-protocol/curation-protocol',
        'curation-protocol/curation-factory',
        'curation-protocol/curator',
        'curation-protocol/curator-skeleton-NFT',
        'curation-protocol/default-metadata-renderer',
        'curation-protocol/CuratorStorageV1'
      ],
    },
    {
      type: 'category',
      label: 'Guides',
      collapsed: true,
      items: [
        'guides/wallet-setup', 
        'guides/getting-started-with-github', 
        'guides/vercel-setup',
        'guides/visual-studio-code-setup',
        'guides/exploring-git',
        'guides/exploring-git-locally',
        'guides/installing-node',
        'guides/assemble-package',
      ],
    },
    {
      type: 'category',
      label: 'Glossary',
      collapsed: true,
      items: [
      'guides/glossary',]
    }
  ],
  guides: [
    {
    type: 'category',
    label: 'Getting Started',
    collapsed: true,
    items: [
      'guides/neosound-quick-start',
      'guides/curation-protocol-quickstart',
    ],
  },
  {
    type: 'category',
    label: 'Curation Protocol',
    collapsed: true,
    items: [
      'curation-protocol/curation-protocol',
      'curation-protocol/curation-factory',
      'curation-protocol/curator',
      'curation-protocol/curator-skeleton-NFT',
      'curation-protocol/default-metadata-renderer',
      'curation-protocol/CuratorStorageV1'
    ],
  },
  {
    type: 'category',
    label: 'Guides',
    collapsed: true,
    items: [
      'guides/wallet-setup', 
      'guides/getting-started-with-github', 
      'guides/vercel-setup',
      'guides/visual-studio-code-setup',
      'guides/exploring-git',
      'guides/exploring-git-locally',
      'guides/installing-node',
      'guides/assemble-package',
    ],
  },
  {
    type: 'category',
    label: 'Glossary',
    collapsed: true,
    items: [
    'guides/glossary',]
  }
],
  curationprotocol:  [
    {
      type: 'category',
      label: 'Getting Started',
      collapsed: true,
      items: [
        'guides/neosound-quick-start',
        'guides/curation-protocol-quickstart',
      ],
    },
    {
      type: 'category',
      label: 'Curation Protocol',
      collapsed: true,
      items: [
        'curation-protocol/curation-protocol',
        'curation-protocol/curation-factory',
        'curation-protocol/curator',
        'curation-protocol/curator-skeleton-NFT',
        'curation-protocol/default-metadata-renderer',
        'curation-protocol/CuratorStorageV1'
      ],
    },
    {
      type: 'category',
      label: 'Guides',
      collapsed: true,
      items: [
        'guides/wallet-setup', 
        'guides/getting-started-with-github', 
        'guides/vercel-setup',
        'guides/visual-studio-code-setup',
        'guides/exploring-git',
        'guides/exploring-git-locally',
        'guides/installing-node',
        'guides/assemble-package',
      ],
    },
    {
      type: 'category',
      label: 'Glossary',
      collapsed: true,
      items: [
      'guides/glossary',]
    }
  ],
  guides: [
    {
      type: 'category',
      label: 'Getting Started',
      collapsed: true,
      items: [
        'guides/neosound-quick-start',
        'guides/curation-protocol-quickstart',
      ],
    },
    {
      type: 'category',
      label: 'Curation Protocol',
      collapsed: true,
      items: [
        'curation-protocol/curation-protocol',
        'curation-protocol/curation-factory',
        'curation-protocol/curator',
        'curation-protocol/curator-skeleton-NFT',
        'curation-protocol/default-metadata-renderer',
        'curation-protocol/CuratorStorageV1'
      ],
    },
    {
      type: 'category',
      label: 'Guides',
      collapsed: true,
      items: [
        'guides/wallet-setup', 
        'guides/getting-started-with-github', 
        'guides/vercel-setup',
        'guides/visual-studio-code-setup',
        'guides/exploring-git',
        'guides/exploring-git-locally',
        'guides/installing-node',
        'guides/assemble-package',
      ],
    },
    {
      type: 'category',
      label: 'Glossary',
      collapsed: true,
      items: [
      'guides/glossary',]
    }
  ],
}
